[package]
name = "ci-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.32.0"
eframe = { version = "0.32.0", features = [
  "default_fonts",
  "wayland",
] }

ci-lisp = { path = "../ci-lisp" }
clap = { version = "4.5.43", features = ["derive"] }
