[package]
name = "ci-term"
version = "0.1.0"
edition = "2024"

[dependencies]
ci-lisp = { path = "../ci-lisp" }
clap = { version = "4.5.44", features = ["derive"] }
reedline = "0.41.0"
thiserror = "2.0.13"
